language: c

compiler:
  - gcc
  - clang

before_script: ./buildrump.sh checkout

env:
  - LIBTYPE='MKPIC=no' DEBUG=''
  - LIBTYPE='MKSTATICLIB=no' DEBUG=''
  - LIBTYPE='MKSTATICLIB=no' DEBUG='-DDD'

script:
  -  dirsuf=${LIBTYPE}.${DEBUG}
  -  ./buildrump.sh -o obj.${dirsuf} -d rump.${dirsuf} -qq -j16 \
       -V ${LIBTYPE} ${DEBUG} fullbuild tests
